### ISSUE TITLE
Diff colors

### ISSUE THREAD

**Issue by lourenci** [savq/melange#12]
First of all, thanks for this colorscheme. I think it is one of the best dark themes out there, if not the best. It's all balanced. My coworkers always ask the name of it in a pair session. Please, make the palette more accessible for ports to other text editors. You did a great job here.

IMHO, this colorscheme fails just in one category: the diff colors. It's hard to tell what has changed at a glance.
I don't understand anything about colors, so I don't know what to suggest to help with this. Maybe, some background colors?

**Comment by savq** [comment]
> First of all, thanks for this colorscheme

Thanks for using it!

-----

About the diff colors, I agree that right now they don't look very good. I didn't put much thought into it. I'll see what other colorschemes are using, hopefully I'll find a useful convention.

I think Neovim will change the diff algorithm in the future, so that might help too.
